### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by maxim19116** [Yardanico/puremine#11]
ImportError: No module named plugin

**Comment by TiberiumPY** [comment]
@maxim19116 Python 2?
Просто дело в том, что я не разрабатываю этот сервер, и тут почти ничего нельзя делать (можно только писать в чат + двигаться локально, при этом других игроков не видно и земли нет ВООБЩЕ)

**Comment by maxim19116** [comment]
А мне что нужно? Это как-раз мне и надо.
